services:
  keycloak:
    container_name: keycloak-booking.json
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - 80:8080
      - 8443:8443
    volumes:
      - ./keycloak/cert/keycloak.pem:/etc/x509/https/tls.crt
      - ./keycloak/cert/keycloakKey.pem:/etc/x509/https/tls.key
      - ./keycloak/realm/booking.json:/opt/keycloak/data/import/booking-realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    networks:
      - local-network
    command:
      - "start-dev"

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"


networks:
  local-network:
    driver: bridge

volumes:
  keycloak:
    driver: local
  openldap:
    driver: local