package com.booking.project.model.enums;

public enum AdminPermissions {

    PENDING_ACCOMMODATION_READ,
    PENDING_ACCOMMODATION_STATUS_UPDATE,

    ACCOMMODATION_COMMENT_DELETE,
    ACCOMMODATION_COMMENT_STATUS_UPDATE,
    REPORTED_ACCOMMODATION_COMMENT_READ,
    PENDING_ACCOMMODATION_COMMENT_READ,



}
