package com.booking.project.model.enums;

public enum AdminPermissions {

    PENDING_ACCOMMODATION_READ,
    PENDING_ACCOMMODATION_STATUS_UPDATE,

    COMMENT_DELETE,
    COMMENT_STATUS_UPDATE,
    REPORTED_COMMENT_READ,
    PENDING_COMMENT_READ,

    ADMIN_UPDATE,
    BLOCK_USER,
    REPORTED_USER_READ,

}
