package com.booking.project.model.enums;

public enum GuestPermissions {

    CALENDAR_READ,

    VISITED_ACCOMMODATION_READ,

    COMMENT_WRITE,
    COMMENT_READ,
    COMMENT_DELETE,

    MY_COMMENT_READ,

    FAVOURITE_READ,
    FAVOURITE_WRITE,
    FAVOURITE_DELETE,

    NOTIFICATION_READ,
    NOTIFICATION_STATUS_UPDATE,
    NOTIFICATION_STATUS_READ,

    // TODO: SOLVE MY RESERVATIONS PROBLEM

    RESERVATION_WRITE,
    RESERVATION_PRICE_READ,
    PENDING_RESERVATION_DELETE,
    ACCEPTED_RESERVATION_DELETE,
}
