package com.booking.project.model.enums;

public enum GuestPermissions {

    CALENDAR_READ,

    VISITED_ACCOMMODATION_READ,

    ACCOMMODATION_COMMENT_WRITE,
    ACCOMMODATION_COMMENT_READ,
    ACCOMMODATION_COMMENT_DELETE,

    MY_ACCOMMODATION_COMMENT_READ


}
