package com.booking.project.model.enums;

public enum HostPermissions {

    ACCOMMODATION_WRITE,
    ACCOMMODATION_DELETE,
    ACCOMMODATION_UPDATE,

    MY_ACCOMMODATION_READ,

    PRICE_LIST_WRITE,
    PRICE_LIST_UPDATE,
    PRICE_LIST_READ,

    ANALYTICS_READ,

    COMMENT_REPORT,
    REPORT_MESSAGE_WRITE,

    IMAGE_WRITE,

    NOTIFICATION_READ,
    NOTIFICATION_STATUS_UPDATE,
    NOTIFICATION_STATUS_READ,

}
